### ISSUE TITLE
'ncol(x)' is not equal to 'length(clusters)'

### ISSUE THREAD

**Issue by scottgigante** [theislab/scib#192]
Can't quite work out why this is happening, but I'm getting an error every time I normalize this dataset.

```
>>> import scIB
>>> import openproblems
>>> adata = openproblems.tasks.multimodal_data_integration.datasets.citeseq_cbmc(test=True)
>>> scIB.preprocessing.normalize(adata)
/home/scottgigante/.local/lib/python3.6/site-packages/scanpy/neighbors/__init__.py:121: FutureWarning: This location for 'distances' is deprecated. It has been moved to .obsp[distances], and will not be accesible here in a future version of anndata.
  adata.uns['neighbors']['distances'] = neighbors.distances
/home/scottgigante/.local/lib/python3.6/site-packages/scanpy/neighbors/__init__.py:122: FutureWarning: This location for 'connectivities' is deprecated. It has been moved to .obsp[connectivities], and will not be accesible here in a future version of anndata.
  adata.uns['neighbors']['connectivities'] = neighbors.connectivities
/home/scottgigante/.local/lib/python3.6/site-packages/scanpy/tools/_louvain.py:107: FutureWarning: This location for 'connectivities' is deprecated. It has been moved to .obsp[connectivities], and will not be accesible here in a future version of anndata.
  adjacency = adata.uns['neighbors']['connectivities']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scottgigante/.local/lib/python3.6/site-packages/scIB/preprocessing.py", line 170, in normalize
    size_factors = ro.r(f'computeSumFactors(data_mat, clusters = input_groups, min.mean = {min_mean})')
  File "/home/scottgigante/.local/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 416, in __call__
    res = self.eval(p)
  File "/home/scottgigante/.local/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/home/scottgigante/.local/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/scottgigante/.local/lib/python3.6/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/home/scottgigante/.local/lib/python3.6/site-packages/rpy2/rinterface.py", line 624, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in .calculate_sum_factors(x, ..., subset.row = subset.row) :
  'ncol(x)' is not equal to 'length(clusters)'
```

[adata.zip](https://github.com/theislab/scib/files/5366010/adata.zip)

**Comment by scottgigante** [comment]
Proposed solution: throw an intuitive error in `adata.X.min(axis=1) == 0`

**Comment by LuckyMD** [comment]
So the error seems to suggest that the number of cluster assignments does not equal the number of cells. This suggests that maybe a cell has 0 expression and therefore is automatically removed by either `anndata2ri` or the `computeSumFactors()` function in `scran`. Does that sounds like it could be the case in the data?

I think the error would therefore more likely be in `adata.X.sum(axis=0) == 0` (note that rows in `adata.X` are transferred to columns in the R object, as the conventions are switched here.

**Comment by scottgigante** [comment]
Yes, I'm fairly sure you're right. This dataset was deeply subsampled so likely had zeros on both rows and columns.

**Comment by LuckyMD** [comment]
Now addressed in #194

**Comment by LuckyMD** [comment]
#194 is merged
