### ISSUE TITLE
label_key not found during metrics steps for scanorama_full

### ISSUE THREAD

**Issue by ilibarra** [theislab/scib#209]
During the metrics step in scanorama the label_ley (`patient`) might be missing in the integrated object. In this case, I think it causes an error that stops the metrics calculation.

Is this expected behavior? I suspect that for some reason the label was not propagated to the integrated object. The column found in the input ifle `integration_benchmark_input_CP_log1p.h5ad`.

```Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	metrics_single
	1

[Mon Feb  8 08:54:54 2021]
Job 0: 
        Metrics hvg=hvg,method=scanorama,o_type=full,scaling=unscaled,scenario=CP
        output: CP/metrics/unscaled/hvg/scanorama_full.csv
        

ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/metrics.py', '-u', 'pancreatic_cancer/data/integration_benchmark_input_CP_log1p.h5ad', '-i', 'CP/integration/unscaled/hvg/scanorama.h5ad', '-o', 'CP/metrics/unscaled/hvg/scanorama_full.csv', '-m', 'scanorama', '-b', 'patient', '-l', 'label', '--type', 'full', '--hvgs', '2000', '--organism', 'human', '--assay', 'expression', '-v']' command failed.  (See above for error)
During startup - Warning messages:
1: package ‘methods’ was built under R version 3.6.1 
2: package ‘datasets’ was built under R version 3.6.1 
3: package ‘utils’ was built under R version 3.6.1 
4: package ‘grDevices’ was built under R version 3.6.1 
5: package ‘graphics’ was built under R version 3.6.1 
6: package ‘stats’ was built under R version 3.6.1 
/home/icb/ignacio.ibarra/miniconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "/home/icb/ignacio.ibarra/miniconda3/envs/scIB-python/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'patient'
```

Thanks,

**Comment by LuckyMD** [comment]
This looks like your config is incorrectly set up to work with the integration output you have for scanorama. I'm not sure what you have stored in your integrated object. Can you show `adata.obs` output?

Also, `label_key` would typically be cell type for us... and `batch_key` would normally be batch/patient.

**Comment by ilibarra** [comment]
adata.obs for input and scanorama.
```
scib_input = sc.read_h5ad('data/integration_benchmark_input_CP_log1p.h5ad')
scib_input.obs[['patient', 'underlying.cause', 'pathology.report', 'batch', 'label']]
```
![image](https://user-images.githubusercontent.com/2761796/107202780-df0f6280-69fa-11eb-891f-94d98f5a5185.png)
```
scanorama_full = sc.read_h5ad('scIB_run/CP/integration/unscaled/hvg/scanorama.h5ad')
scanorama_full.obs
```
![image](https://user-images.githubusercontent.com/2761796/107202733-cd2dbf80-69fa-11eb-958d-4d8b89c1dc43.png)

The DATA_SCENARIO for this case in `config.yaml` is
```
DATA_SCENARIOS:
  CP:
    batch_key: batch
    label_key: label
    assay: expression
    organism: human
    file: data/integration_benchmark_input_CP_log1p.h5ad
```

I'll keep debugging I suspect now it is a scanorama version issues.

**Comment by ilibarra** [comment]
In case it helps `scanorama`s version in `scIB-python` is `1.6`
```
In [1]: import scanorama
In [2]: scanorama.__version__
Out[2]: '1.6'
```

**Comment by LuckyMD** [comment]
Ah, yes... we have a fix for this and some other issues in scanorama in our `metrics.py` script. I think this has now been fixed in newer versions of scanorama as well though. We were initially using a patched version of 1.4... but now we have 1.7 as recommended install (our patch was included from 1.7) in our scIB-python environment. There's a small change to the Scanorama function though to make this work.

**Comment by LuckyMD** [comment]
The scIB-python PR is currently being worked on by @mumichae and should be merged very soon.

**Comment by mumichae** [comment]
@ilibarra the `scIB-python` environment has been updated  in #147 . Could you update your `scIB-python` environment, preferably by removing it completely and reinstalling it?

```console
conda deactivate
conda env remove -n scIB-python
conda env create -f <path-to-scib-repo>/envs/scIB-python.yaml
```
Double-check that the scanorama version is 1.7
Also, you'll need to install kBET manually in R of `scIB-python`

```R
devtools::install_github('theislab/kBET', quiet=T)
```

Hope this resolves the issue!

**Comment by ilibarra** [comment]
Hey @mumichae 

Thanks for checking on this. So far I have been able to repeat the running of scanorama but I get stuck during the `save_embedding.py` step

```
[Tue Mar  2 14:09:30 2021]
Job 56: 
        SAVE EMBEDDING
        Scenario: all unscaled full_feature
        Method: scanorama embed
        Input: /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/integration/unscaled/full_feature/scanorama.h5ad
        Output: /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/embeddings/unscaled/full_feature/scanorama_embed.csv /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/embeddings/unscaled/full_feature/scanorama_embed_batch.png /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/embeddings/unscaled/full_feature/scanorama_embed_labels.png

connect localhost port 6000: Connection refused
connect localhost port 6000: Connection refused
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/save_embeddings.py', '--input', '/storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/integration/unscaled/full_feature/scanorama.h5ad', '--outfile', '/storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/embeddings/unscaled/full_feature/scanorama_embed.csv', '--method', 'scanorama', '--batch_key', 'batch', '--label_key', 'label', '--result', 'embed']' command failed.  (See above for error)
qt.qpa.xcb: could not connect to display localhost:12.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

/home/icb/ignacio.ibarra/miniconda3/envs/scIB-python/.tmph1easou4: line 3: 13848 Aborted                 (core dumped) python scripts/save_embeddings.py --input /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/integration/unscaled/full_feature/scanorama.h5ad --outfile /storage/groups/ml01/workspace/ignacio.ibarra/theislab/pancreatic_cancer/data/scIB_run/all/embeddings/unscaled/full_feature/scanorama_embed.csv --method scanorama --batch_key batch --label_key label --result embed
```

I think this is related to the `QT_DEBUG_PLUGINS` variable but trying to wonder how to modify it. I will try this in my interactive version first. If you think this has to be done in the pipelin scripts please let me know.

Thanks a lot!

**Comment by LuckyMD** [comment]
Thanks for this comment @ilibarra! @danielStrobl or @mumichae could you add this to the env setup description? I guess it now needs to go into `scib` and `scib-pipeline`.

**Comment by mumichae** [comment]
@ilibarra Are you perhaps working on a cluster?

**Comment by mumichae** [comment]
@LuckyMD I think that should only go into `scib-pipeline`, because we transferred all the environments there

**Comment by mumichae** [comment]
@LuckyMD I guess this issue can be closed?
