### ISSUE TITLE
env for scib

### ISSUE THREAD

**Issue by z5ouyang** [theislab/scib#228]
Hi there,
Which env should the scib package to be installed?

Thanks

**Comment by LuckyMD** [comment]
Hi @z5ouyang, 
We have 2 environments that we are using at the moment: a python and an R environment (R-conversion is no longer needed). The installation instructions for these are available in the main README and the environment.yaml files [here](https://github.com/theislab/scib/tree/master/envs). The `scib` package only needs to be in the `scIB-python` environment, but that should already be stated in the `.yaml` file for that environment.

**Comment by z5ouyang** [comment]
after install scIB into ```scIB-python``` env, still errors:
```python
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runPP.py', '-i', '/home/zouyang/scIB/Data/human_pancreas/human_pancreas_norm_withCounts.h5ad', '-o', '/home/zouyang/scIB/run/outs/pancreas/prepare/scaled/full_feature/adata_pre.h5ad', '-b', 'tech', '--hvgs', '0', '-s']' command failed.  (See above for error)
/home/zouyang/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "scripts/runPP.py", line 5, in <module>
    import scIB
ModuleNotFoundError: No module named 'scIB'

ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runPP.py', '-i', '/home/zouyang/scIB/Data/human_pancreas/human_pancreas_norm_withCounts.h5ad', '-o', '/home/zouyang/scIB/run/outs/pancreas/prepare/unscaled/full_feature/adata_pre.h5ad', '-b', 'tech', '--hvgs', '0']' command failed.  (See above for error)
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runPP.py', '-i', '/home/zouyang/scIB/Data/human_pancreas/human_pancreas_norm_withCounts.h5ad', '-o', '/home/zouyang/scIB/run/outs/pancreas/prepare/unscaled/hvg/adata_pre.h5ad', '-b', 'tech', '--hvgs', '2000']' command failed.  (See above for error)
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runPP.py', '-i', '/home/zouyang/scIB/Data/human_pancreas/human_pancreas_norm_withCounts.h5ad', '-o', '/home/zouyang/scIB/run/outs/pancreas/prepare/scaled/full_feature/adata_pre.RDS', '-b', 'tech', '--hvgs', '0', '-s', '-r', '-l']' command failed.  (See above for error)
/home/zouyang/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "scripts/runPP.py", line 5, in <module>
    import scIB
ModuleNotFoundError: No module named 'scIB'

/home/zouyang/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "scripts/runPP.py", line 5, in <module>
    import scIB
ModuleNotFoundError: No module named 'scIB'
...
```

**Comment by mumichae** [comment]
From what I can see, scIB isn't installed the environment. Are you following the README of the [scib-pipeline](https://github.com/theislab/scib-pipeline) repository? Let me know if you run into any issues.

**Comment by LuckyMD** [comment]
We should clarify in this README that env installation is explained in the scib-pipeline repo @mumichae

**Comment by z5ouyang** [comment]
Thanks all for the reply! I am wondering, should I move the issue to 'scib-pipeline'?
I am just try to reproduce the results for the human_pancreas data for now.

After install 'scIB' into ```scIB-python```, new erros:
```python
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runIntegration.py', '-i', '/home/zouyang/scIB/run/outs/pancreas/prepare/unscaled/hvg/adata_pre.h5ad', '-o', '/home/zouyang/scIB/run/outs/pancreas/integration/unscaled/hvg/desc.h5ad', '-b', 'tech', '--method', 'desc', '-v', '2000']' command failed.  (See above for error)
/home/zouyang/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "scripts/runIntegration.py", line 79, in <module>
    runIntegration(file, out, run, hvg, batch, celltype)
  File "scripts/runIntegration.py", line 36, in runIntegration
    integrated = method(adata, batch)
  File "/camhpc/home/zouyang/scIB/install/scib/scIB/integration.py", line 332, in runDESC
    import desc
ModuleNotFoundError: No module named 'desc'
```

And found 'desc==2.0.3' was commanded out in 'scIB-python.yml', installing it (require keras==2.1.0) manually cause incompatible with "scgen==1.1.5" which require keras==2.3.

**Comment by z5ouyang** [comment]
scib cannot be installed by scIB-python.yml:

```python
Downloading and Extracting Packages
python-dateutil-2.8. | 220 KB    | ########################################################################################################### | 100%
testpath-0.4.4       | 85 KB     | ########################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - b''                                                                                                                        / b''                                                                                                                                                 done
Ran pip subprocess with arguments:
['/home/zouyang/anaconda3/envs/scIB-python/bin/python', '-m', 'pip', 'install', '-U', '-r', '/camhpc/home/zouyang/scIB/install/scib/envs/condaenv.n7xxxrzz.requirements.txt']
Pip subprocess output:
Collecting git+git://github.com/theislab/scib.git (from -r /camhpc/home/zouyang/scIB/install/scib/envs/condaenv.n7xxxrzz.requirements.txt (line 1))
  Cloning git://github.com/theislab/scib.git to /tmp/pip-req-build-9js59z5t

Pip subprocess error:
  Running command git clone -q git://github.com/theislab/scib.git /tmp/pip-req-build-9js59z5t
  github.com[0: 140.82.113.3]: errno=Connection timed out
  fatal: unable to connect a socket (Connection timed out)
WARNING: Discarding git+git://github.com/theislab/scib.git. Command errored out with exit status 128: git clone -q git://github.com/theislab/scib.git /tmp/pip-req-build-9js59z5t Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/theislab/scib.git /tmp/pip-req-build-9js59z5t Check the logs for full command output.
```

**Comment by LuckyMD** [comment]
This looks like it might have to do with your internet connection, no? You have a `Connection timed out` error during the github clone.

**Comment by LuckyMD** [comment]
As for DESC... it might be best to run this separately for now (as well as scGen). These methods don't really have easy dependencies.

**Comment by mumichae** [comment]
It seems that git is having some issues cloning the `scib` repository. Try cloning it manually and installing it into `scIB-python`

```
git clone https://github.com/theislab/scib.git
conda activate scIB-python
cd scib
pip install -e .
```

(The `-e` links the dependency directly to the source code. It is optional but recommended while `scib` is still being actively developed)

**Comment by mumichae** [comment]
As this PR is outdated, I'm going to close it. Please refer to the https://github.com/theislab/scib-pipeline for the code and instructions on the pipeline
